//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baja_Industriales.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int ID { get; set; }
        public Nullable<int> Cod_Sucursal { get; set; }
        public Nullable<int> Cod_Producto { get; set; }
        public Nullable<int> Stock { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
