//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baja_Industriales.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int Cod_Empleado { get; set; }
        public string Tipo_Usuario { get; set; }
        public string Contraseña { get; set; }
        public string Nombre { get; set; }
        public string A_Paterno { get; set; }
        public string A_Materno { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Cod_Sucursal { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
